name: Release Bromite CI
permissions:
  contents: write
      
on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'uazo/bromite SHA'
        required: true
        default: '0a8ff322d6e9d738f7b2fa52618b178081bd100d'
      build:
        description: 'arch [arm64/x64]'
        required: true
        default: 'arm64'
      type:
        description: 'runner? [dev/ci]'
        required: true
        default: 'ci'
        
env:
  BROMITE_SHA: ${{ github.event.inputs.sha }}
  REMOVEDOCKERSUPPORT: true
  USELOCALIMAGE: true
  GOMAJOBS: 60
  
jobs:
  release:
    runs-on: ${{ github.event.inputs.type }}
    env:
      OUTPUTFILE: /storage/images/android/${{ github.event.inputs.build }}/${{ github.event.inputs.sha }}
      APK: ${{ github.event.inputs.build }}_ChromePublic.apk
        
    steps:
      - name: Prepare container
        run: |
          wget https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip
          unzip pup_v0.4.0_linux_amd64.zip && rm pup_v0.4.0_linux_amd64.zip
          BRANCH=$(curl https://github.com/uazo/bromite/branch_commits/$BROMITE_SHA | ./pup -p li.branch:last-child a text{} | xargs)
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

          wget https://github.com/cli/cli/releases/download/v2.4.0/gh_2.4.0_linux_amd64.tar.gz
          tar xfz gh_2.4.0_linux_amd64.tar.gz

      - name: Checkout 'uazo/buildtools'
        uses: actions/checkout@v2
        with:
            repository: 'uazo/bromite-buildtools'
            path: 'bromite'
            fetch-depth: 1
            
      - name: Copy artifacts
        shell: bash
        run: |
          sudo cp ${{ env.OUTPUTFILE }}/apks/ChromePublic.apk ChromePublic.apk
          sudo chown runner ChromePublic.apk
          mv ChromePublic.apk $APK

      - name: Create release
        shell: bash
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh_2.4.0_linux_amd64/bin/gh auth login --with-token
          
          cd bromite
          VERSION=v$(cat ${{ env.OUTPUTFILE }}/RELEASE)-${{ github.event.inputs.build }}
          ../gh_2.4.0_linux_amd64/bin/gh release create $VERSION-$BROMITE_SHA \
            ../$APK --notes "" -p
